version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./airflow_home:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./practica_creativa:/opt/airflow/practica_creativa
    command: >
      bash -c "
      airflow db init &&
      airflow scheduler"
    depends_on:
      - postgres

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    ports:
      - "8080:8080"
    volumes:
      - ./airflow_home:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./practica_creativa:/opt/airflow/practica_creativa
    command: >
      bash -c "
      airflow users create --username admin --firstname Jack --lastname Sparrow --role Admin --email example@mail.org &&
      airflow webserver"
    depends_on:
      - postgres

volumes:
  postgres_data:
