version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - flight_network
    restart: always

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    container_name: kafka
    environment:
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://192.168.1.100:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
    - "9092:9092"  # Exponer el puerto para acceso externo
    networks:
      - flight_network
    restart: always
    depends_on:
    - zookeeper
    entrypoint: /bin/sh -c "until nc -z -v -w30 zookeeper 2181; do echo 'Esperando a Zookeeper...'; sleep 5; done; /usr/bin/start-kafka.sh & echo 'Esperando a Kafka...'; until kafka-topics.sh --list --bootstrap-server kafka:9092; do sleep 5; done; kafka-topics.sh --create --topic flight_delay_classification_request --partitions 1 --replication-factor 1 --bootstrap-server kafka:9092; wait"


  mongo:
    image: mongo:6.0  # Usar la versión 6.0 de MongoDB
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - flight_network
    volumes:
      - ./init-data:/init-data:ro
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d:ro
    restart: always
    command: ["mongod"]

  mongo-seed:
    image: mongo:6.0  # Usa la imagen de Mongo directamente
    container_name: mongo-seed
    depends_on:
      - mongo
    networks:
      - flight_network
    volumes:
      - ./mongo-seed:/init-data  # Monta el directorio con los datos
    command: /bin/bash -c "/init-data/import_distances.sh"  # Ejecuta el script de importación
    restart: on-failure

  prediction_app:
    build:
      context: ./prediction
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PROJECT_HOME=/app/practica
    volumes:
      - ./practica:/app/practica
    command: >
      bash -c "
      cd /app/practica/resources/web &&
      python3 predict_flask.py"
    networks:
      - flight_network

  
  proxy:
    image: node:18-alpine
    container_name: proxy
    command: "node /client/node.js"
    ports: 
      - "3000:3000"
    volumes:
     - ./spark/client:/client
    networks:
      - flight_network

  #Spark Master
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    
    volumes:
      - ./practica:/spark/work-dir/practica
    networks:
      - flight_network
    

  #Spark Worker 1
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./practica:/spark/work-dir/practica
    networks:
      - flight_network
    

  #Spark Worker 2
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./practica:/spark/work-dir/practica
    networks:
      - flight_network
    

  spark-submit:
    build: ./spark
    container_name: spark-submit
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    ports:
      - "4040:4040"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SERVER=proxy"
    volumes:
      - ./practica:/spark/work-dir/practica
    command: >
      /spark/bin/spark-submit
      --class es.upm.dit.ging.predictor.MakePrediction
      --master spark://spark-master:7077
      --packages org.mongodb.spark:mongo-spark-connector_2.12:10.1.1,org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0
      /spark/work-dir/practica/flight_prediction/target/scala-2.12/flight_prediction_2.12-0.1.jar

    networks:
      - flight_network


  
networks:
   flight_network:
      driver: "bridge"
      name: "flight_network" 

volumes:
  mongo-data:

